apiVersion: v1
kind: Secret

metadata:
  name: ecommerce-secret
  namespace: ecommerce

type: Opaque

stringData:
  DB_USER: mypostgres
  DB_PASSWORD: DB_PASSWORD
  JWT_SECRET: 2b77ee91cbfa334477394b578d65bae7661c6fab29ae3cbf073a69a7d060ddcc8c5a32a561b1c0b55c98d1a095f35855efd752d3fe7ff3884d115767dfca24f6