apiVersion: apps/v1
kind: Deployment

metadata:
  name: product-service
  namespace: ecommerce

spec:
  replicas: 1

  selector:
    matchLabels:
      app: product-service
  
  template:
    metadata:
      labels:
        app: product-service
    
    spec:
      containers:
        - name: product-service
          image: diptidocker99/product-service:1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: ecommerce-config
            - secretRef:
                name: ecommerce-secret
          
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            
            limits:
              cpu: "500m"
              memory: "512Mi"

          livenessProbe:
            httpGet:
              path: /health
              port: 3001

            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 10
            periodSeconds: 5  