apiVersion: v1
kind: ConfigMap

metadata:
  name: ecommerce-config
  namespace: {{ .Values.namespace }}

data:
  DB_HOST: postgres
  DB_PORT: "5432"
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  KAFKA_BROKER: kafka:9092