apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecommerce-ingress
  namespace: {{ .Values.namespace }}

spec:
  ingressClassName: nginx

  rules:
    - http:
        paths:

          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: {{ .Values.auth.port }}

          - path: /orders
            pathType: Prefix
            backend:
              service:
                name: order-service
                port:
                  number: {{ .Values.order.port }}

          - path: /products
            pathType: Prefix
            backend:
              service:
                name: product-service
                port:
                  number: {{ .Values.product.port }}
          
          - path: /inventory
            pathType: Prefix
            backend:
              service:
                name: inventory-service
                port:
                  number: {{ .Values.inventory.port }}