apiVersion: v1
kind: Secret

metadata:
  name: ecommerce-secret
  namespace: {{ .Values.namespace }}

type: Opaque

stringData:
  DB_USER: {{ .Values.postgres.user }}
  DB_PASSWORD: {{ .Values.postgres.password }}
  JWT_SECRET: {{ .Values.auth.jwtsecret }}