apiVersion: v1
kind: Service

metadata:
  name: notification-service
  namespace: {{ .Values.namespace }}

spec:
  selector:
    app: notification-service
  
  ports:
    - port: {{ .Values.notification.port }}
      targetPort: {{ .Values.notification.port }}
